# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [34]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr2d = np.reshape(arr, (2,5 ))
print(arr2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [35]:
arr1 = np.array([[0, 1, 2, 3, 4],  [5, 6, 7, 8, 9]])
arr2 = np.array([[1, 1, 1, 1, 1],  [1, 1, 1, 1, 1]])
vstk = np.vstack((arr1,arr2))
print(vstk)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [36]:
arr1 = np.array([[0, 1, 2, 3, 4],  [5, 6, 7, 8, 9]])
arr2 = np.array([[1, 1, 1, 1, 1],  [1, 1, 1, 1, 1]])
hstk = np.hstack((arr1,arr2))
print(hstk)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [37]:
arr2d = np.array([[0, 1, 2, 3, 4],  [5, 6, 7, 8, 9]])
arr2d.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [38]:
arr2d = np.array( [[ 0,1, 2 , 3 , 4],
 [ 5 , 6 , 7  ,8 , 9],
 [10, 11, 12, 13, 14]])
arr2d.ravel()


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [39]:
arr1d = np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
arr1d.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [40]:
arr_5x = np.arange(25).reshape(5,5)

print(np.square(arr_5x))

[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]
 [400 441 484 529 576]]


## Question:8

### Create 5x6 an array and find the mean?

In [41]:
arr_5x6 = np.arange(30).reshape(5,6)
print(np.mean(arr_5x6))

14.5


## Question:9

### Find the standard deviation of the previous array in Q8?

In [42]:
np.std(arr_5x6)

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [43]:
np.median(arr_5x6)

14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [44]:
np.transpose(arr_5x6)

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [45]:
arr_4x4 = np.arange(16).reshape(4,4)
diag_sum = np.sum(np.diagonal(arr_4x4) )
diag_sum

30

## Question:13

### Find the determinant of the previous array in Q12?

In [46]:
result =  np.linalg.det(arr_4x4)
result

-2.9582283945787796e-30

## Question:14

### Find the 5th and 95th percentile of an array?

In [47]:
percentile_arr=np.arange(1,100)
print(np.percentile(percentile_arr, 5))
print(np.percentile(percentile_arr, 95))

5.9
94.1


## Question:15

### How to find if a given array has any null values?

In [48]:
arr = np.arange(16).reshape(4,4)

#is_null = np.NaN(arr)
print(np.isnan(arr).any()) 

False
